
use strict;
use warnings;

use Module::Build 0.3601;


my %module_build_args = (
  "build_requires" => {
    "Module::Build" => "0.3601"
  },
  "configure_requires" => {
    "Module::Build" => "0.3601"
  },
  "dist_abstract" => "More color themes",
  "dist_author" => [
    "Steven Haryanto <stevenharyanto\@gmail.com>"
  ],
  "dist_name" => "Text-ANSITable-ColorTheme-Extra",
  "dist_version" => "0.09",
  "license" => "perl",
  "module_name" => "Text::ANSITable::ColorTheme::Extra",
  "recommends" => {},
  "recursive_test_files" => 1,
  "requires" => {
    "Convert::Color" => 0,
    "Data::Clone" => 0,
    "SHARYANTO::Color::Util" => "0.47",
    "Text::ANSITable" => "0.10",
    "Text::ANSITable::ColorThemeUtil" => "0.10",
    "perl" => "5.010001"
  },
  "script_files" => []
);


my $build = Module::Build->new(%module_build_args);

$build->create_build_script;
