---
abstract: 'More color themes'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ANSITable-ColorTheme-Extra
requires:
  Convert::Color: 0
  Data::Clone: 0
  SHARYANTO::Color::Util: 0.47
  SHARYANTO::ColorTheme::Util: 0
  Text::ANSITable: 0.22
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Text-ANSITable-ColorTheme-Extra
  homepage: https://metacpan.org/release/Text-ANSITable-ColorTheme-Extra
  repository: git://github.com/sharyanto/perl-Text-ANSITable-ColorTheme-Extra.git
version: 0.12
